/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 認証状態とCSRF tokenを取得する
         * @description 未認証でも`200`を返す（取得失敗と未認証を区別するため）。WebはこのresponseのCSRF tokenを
         *     以後の変更操作で`X-CSRF-Token`に付ける。
         */
        get: operations["getSession"];
        put?: never;
        /**
         * メールアドレスとpasswordでloginする
         * @description 成功するとsessionを更新し、新しいCSRF tokenを返す。認証成功から7日で失効し、利用では
         *     延長しない（`expires_at`）。`email_unconfirmed`はpasswordが一致したときだけ返し、一致しなければ
         *     登録の有無やメール確認の状態にかかわらず`invalid_credentials`を返す（登録の有無を明かさない）。
         *     passwordの不一致が10回続くとアカウントをロックし、解除メールを送る。ロック中はpasswordが
         *     一致しても`invalid_credentials`を返す（ロックの有無を明かさない）。ロックは1時間で自動で解け、
         *     解除メールのリンク（`PATCH /api/v1/unlock`）でも解ける。失敗がIPごとに1時間50回を超えると`429`。
         *     退会を受理した利用者もloginでき、
         *     `account_status=deletion_in_progress`のSessionを返す（Webは退会の状況画面へ進める）。
         */
        post: operations["createSession"];
        /**
         * logoutする
         * @description sessionを破棄しCookieを消す。CookieStoreのため、コピー済みCookieの即時失効は保証しない。
         *     未認証で呼んでも`204`を返す。
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * メールアドレスとpasswordで登録する
         * @description 登録済みかどうかにかかわらず同じ`202`を返す（登録の有無を明かさない）。未登録なら確認メールを、
         *     登録済みならログインとpassword再設定を案内するメールを送る。passwordは8〜128文字（文字種は問わない）。
         *     確認メール・案内メールは、確認メールの再送と同じ宛先・IPの制限を受ける。
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 確認メールを再送する
         * @description 宛先の制限（送信元IPと宛先の組ごとに60秒に1回・1時間5回、宛先ごとに1時間20回）に掛かった場合も、
         *     登録の有無にかかわらず同じ`202`を返す。
         *     IPごとの制限（1時間20回）だけ`429`を返す。
         */
        post: operations["resendConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 確認tokenを使ってメールアドレスを確認する
         * @description 確認tokenの有効期限は24時間で、使用後は再利用できない。成功してもloginはしない
         *     （Webはログイン画面へ戻す）。
         */
        patch: operations["confirmEmail"];
        trace?: never;
    };
    "/api/v1/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * password再設定メールを送る
         * @description 確認メールの再送と同じ制限・同じ共通応答。Google専用の利用者には再設定tokenを発行せず、
         *     Googleでのログインを案内するメールを送る（応答は同じ`202`）。
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 再設定tokenと新しいpasswordで再設定する
         * @description 再設定tokenの有効期限は6時間で、使用後は再利用できない。メール未確認の利用者は、再設定に成功すると
         *     確認済みになる（再設定のメールを受け取れたことでメールの所有が示されるため）。成功してもloginはしない
         *     （Webはログイン画面へ戻す）。
         */
        patch: operations["resetPassword"];
        trace?: never;
    };
    "/api/v1/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 解除tokenを使ってアカウントのロックを解く
         * @description loginの失敗が続いてロックしたときに送る解除メールのリンクから使う。成功してもloginはしない
         *     （Webはログイン画面へ戻す）。ロックは1時間で自動でも解ける。解除tokenは1回だけ使える。
         *     token_expiredは返さない（期限が来る前にロックが自動で解けるため）。
         */
        patch: operations["unlockAccount"];
        trace?: never;
    };
    "/auth/google_oauth2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Googleログインを開始する（form POST）
         * @description JSON APIではない。Webは通常のform submitで送り、browserがGoogleへ遷移する。
         *     `intent=reauthenticate`は、Google専用の利用者が退会の前に再認証するときに使う
         *     （有効時間はTASK-006で決める）。退会を受理した利用者も`intent=sign_in`でloginでき、
         *     callbackは`/`へ戻す（Webは`account_status`で退会の状況画面へ進める）。
         *     試行回数の制限（開始がIPごとに1時間50回）に掛かった場合は、JSONの`429`ではなく`auth_error=rate_limited`を付けてredirectする
         *     （form POSTでbrowserが遷移するため）。戻り先は`intent=sign_in`なら`/login`、`reauthenticate`なら
         *     `return_to`（省略時は`/`。loginしたまま退会などの流れへ戻れるようにするため）。
         */
        post: operations["startGoogleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google_oauth2/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Googleからのcallback
         * @description JSON APIではない。認証応答とstateを検証し、SPAへredirectする。成功時は`return_to`
         *     （省略時は`/`）へ戻す。失敗時は`auth_error=<理由>`を付けて、`intent=sign_in`なら`/login`へ、
         *     loginしたままの`intent=reauthenticate`なら`return_to`（省略時は`/`）へ戻す（理由の一覧は
         *     `contracts/README.md`）。
         *
         *     `intent=reauthenticate`では、**Googleが返した利用者（検証済みのprovider/uid）が、いまlogin
         *     している利用者に紐づくGoogleの利用者と一致することを必ず確かめる。**一致しなければsessionも
         *     再認証の時刻も変えず、`return_to`（省略時は`/`）へ`auth_error=google_reauthentication_mismatch`を
         *     付けて戻す。loginしていない状態の`reauthenticate`は`/login?auth_error=google_auth_failed`にする。盗まれたsessionに
         *     別のGoogle利用者で再認証を通し、退会まで進められないようにするため。
         *     Googleが確認済みと返したメールが、メール＋passwordの利用者と一致した場合は
         *     `google_email_conflict`を返し、既存の利用者へも新しい利用者へも接続しない。
         */
        get: operations["googleAuthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 退会を受け付ける
         * @description **まだ受理していない退会では**、password利用者は`current_password`が必須で、送られなければ
         *     `422 validation_failed`、違っていれば`403 reauthentication_failed`を返す。Google専用の利用者
         *     （passwordを持たない）は送らず、代わりに直近のGoogle再認証が必要で、無ければ
         *     `403 google_reauthentication_required`を返す。**受理済みの退会のやり直しでは、bodyを見ずに
         *     （`current_password`の有無も確かめずに）`202`を返す。**
         *
         *     受理の時点で新しい保存・再試行・結果の確定を止め、ゴミ箱の中も含めて本人のデータを消す。
         *     **進行中の処理が0になり、削除が終わるまで完了を返さない。**受理後もsessionは完了まで残し、
         *     Webは`GET /api/v1/account/deletion`で状況を取得する。既に受理済みなら同じ`202`を返す。
         *     `failed`のあとに呼ぶと削除をやり直す。**受理済みの退会のやり直しでは再認証を求めない**
         *     （受理の時点で本人確認が済んでおり、やり直しは同じ削除を再開するだけで対象を広げないため）。
         *     serverも`failed`の削除を自動で再実行するので、利用者がやり直さなくても削除は進む。
         *     sessionを失った場合は、loginし直せば状況の確認とやり直しへ戻れる。
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 退会の状況を取得する
         * @description `completed`は1回だけ返し、同じresponseでsessionを破棄する。以後は`401`になる。
         *     受理していなければ`404`。
         */
        get: operations["getAccountDeletion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recording_attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 録音attemptを発行する（録音開始の受付票）
         * @description 録音開始操作の直前に呼ぶ。serverが受理した時刻が`started_at`になり、Dotの`date`はここから
         *     決まる。Webは`attempt_token`をmemoryにだけ置き、storageへ書かない。1つのattemptは1件の
         *     Dot生成にしか使えず、録り直しでは新しく発行する。serverはattemptを保存しない
         *     （一回性は初回送信で処理の記録の一意制約により担保する）。例外として、Dotの完全削除・退会・
         *     処理の取り消しで処理の記録とDotを消すときは、そのattemptの`id`と期限だけを期限まで残し、
         *     同じattemptでの再送を`attempt_invalid`にする（消したものが作り直されないようにするため）。
         */
        post: operations["createRecordingAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 録音した音声を送り、Dotの生成を始める
         * @description 生成は非同期で、`202`で処理（Generation）を返して終わる。結果は
         *     `GET /api/v1/generations/{generation_id}`で取得する。
         *
         *     attemptは`X-Recording-Attempt` headerで渡す（bodyに入れない）。serverはmultipartを解釈する
         *     前にheaderのattemptを検証し、同じattemptで再び送られた場合は、新しい処理を作らず、multipartの
         *     解釈もS3への保存もせずに既存の処理を返す。例外は既存の処理が`failed`かつ
         *     `failure.kind=upload_incomplete`の場合で、attemptの期限内なら音声を受け取り直す。
         *     同じattemptの処理のDotがゴミ箱の中にある場合と、完全削除・退会・処理の取り消しで消した後の
         *     場合は`422 attempt_invalid`を返す（ゴミ箱の中のDotを返さず、消したものを作り直さないため）。
         *
         *     HTTPの本文はPumaが受け取り終えてからアプリへ渡すため、serverの判定では本文の再送信そのものは
         *     防げない。Webは送り直す前に`GET /api/v1/generations/{id}`（idは録音attemptの`id`）で既存の
         *     処理を確かめる。`404`なら送り直す。`failed`かつ`failure.kind=upload_incomplete`なら、音声が
         *     serverに届いていないので送り直す。それ以外の状態なら送り直さず、その処理を使う。
         *
         *     録音中に認証が失効しても、同じ利用者で入り直せばattemptの期限内は同じattemptで送れる。
         *     別の利用者のattemptは`attempt_invalid`になる。
         */
        post: operations["createDot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        /**
         * 生成の状態を取得する（polling）
         * @description serverは先にDotの有無を見る。同じ処理のDotがあれば、後片付けが残っていても`succeeded`を返す。
         *
         *     `processing`の間は`poll_after_seconds`秒あけて次を取得する。Webは自動の取得を15分で止め、
         *     再表示や利用者の操作で再開する（打ち切っても処理は止まらない）。
         *
         *     文字起こし全文は、受領通知（ACK）の受理後、保持期間の経過後、そのDotの完全削除の受理後、
         *     退会の受理後は返さない。ACK後と期間経過後はDotが残るので`succeeded`と
         *     `transcript.status=unavailable`を返す。完全削除と退会ではDotも残らないので`404`になる。
         *     ゴミ箱の中のDotの処理も`404`。
         */
        get: operations["getGeneration"];
        put?: never;
        post?: never;
        /**
         * Dotになる前の処理を取り消し、預けた音声などを消す
         * @description Dotがまだ無い処理（`processing` / `failed` / `expired`）を取り消す。認可・対象の状態・消す範囲は
         *     `docs/architecture.md`「生成の実行方式」の「処理の取り消し」を正とする。生成へは進めず、預けた
         *     音声・文字起こし結果・文字起こしのjob・処理の記録の削除処理を始める（`privacy.md` §5-1の
         *     「処理の取り消し」）。`202`は削除を受け付けたことを表し、消え終わったことは表さない
         *     （文字起こしのjobが終わるまで消せないなど、完了は遅れ得る）。受理以降、この処理の照会は`404`。
         *     外部へ既に渡った分は取り消せない。
         *
         *     Dotの保存まで終わっている処理は取り消せず`409 generation_completed`を返す（Webは
         *     `DELETE /api/v1/dots/{dot_id}`での完全削除へ案内する）。ただしそのDotがゴミ箱の中なら、照会と
         *     同じく`404`を返す（ゴミ箱のendpoint以外からゴミ箱の中のDotの存在を示さないため）。
         *     存在しない処理・他人の処理・取り消しを受理済みの処理は`404`。応答を失ってDELETEを送り直した
         *     場合も`404`になるので、Webは自分が送った取り消しの再送で`404`を受けたら取り消し済みとして扱う。
         */
        delete: operations["cancelGeneration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 失敗した生成を、録り直さずに再試行する
         * @description `failed`かつ`retryable=true`のときだけ受け付ける。serverが預かっている音声（または文字起こし
         *     結果）から再開するので音声は送らない。`started_at`は変わらない。
         *     `failure.kind=upload_incomplete`の場合は音声がserverに無いため、ここではなく
         *     `POST /api/v1/dots`へ同じattemptで送り直す。
         */
        post: operations["retryGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 端末へ保存し終えた文字起こし全文を、server側から消す
         * @description 文字起こし全文の受領通知（ACK）。Webは全文を`sessionStorage`へ保存し**終えてから**呼ぶ。
         *     serverは文字起こし結果のobjectと文字起こしのjobの削除処理を始め、以後この処理の照会では
         *     全文を返さない（`transcript.status=unavailable`）。server側の全文は戻せない。
         *     `202`は削除を受け付けたことを表し、消え終わったことは表さない。何度呼んでも結果は変わらず、
         *     対象が既に無くても本人の処理なら`202`を返す。Dotそのものは消さない。
         */
        delete: operations["deleteTranscript"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 記録のある日を新しい順に取得する
         * @description 1日を1要素に集約して返す。記録のない日と、すべてのDotがゴミ箱にある日は要素を返さない。
         *     件数にゴミ箱の中のDotを数えない。続きは`next_cursor`で取得し、`null`なら終わり。
         */
        get: operations["listDays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/days/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 今日（Asia/Tokyo）の最新のDotを取得する
         * @description Dayの表示に使う。今日の記録が無ければ`dot_count: 0`で`latest_dot`を省く（取得失敗とは別）。
         *     `date`はserverが決めた今日の日付。
         */
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定した日のDotを取得する
         * @description その時点でゴミ箱の外にある、その日の本人のDotを`started_at`の降順（同値ならidの降順）で返す。
         *     先頭が既定表示する最新のDot。0件でも`200`で`dots: []`を返す（一覧の取得後にその日のDotが
         *     すべてゴミ箱へ移るか完全削除された場合）。Webは「その日に振り返れるDotがない」と示し、
         *     一覧を取り直す。
         */
        get: operations["getDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dots/{dot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dotを完全削除する（戻せない）
         * @description ゴミ箱の内外を問わず受け付ける。そのDotの行と、そのDotを作った処理の音声・文字起こし結果・
         *     文字起こしのjob・処理の記録を消し終えてから`204`を返す。一部だけ消えた状態は成功にせず
         *     `503 deletion_failed`を返す（同じ要求でやり直せる）。RDS自動backupと外部providerに残り得る分は
         *     対象外。存在しない・他人のDotは`404`（応答を失って再送した場合も`404`になる）。
         */
        delete: operations["deleteDotPermanently"];
        options?: never;
        head?: never;
        /**
         * Dotの`sentence`と`summary`を編集する
         * @description 編集前の値は残さない（戻せない）。空文字は許す。`date`・`started_at`・`duration_seconds`は
         *     編集できない（送られても無視せず`422`にする）。ゴミ箱の中のDotは`404`。
         */
        patch: operations["updateDot"];
        trace?: never;
    };
    "/api/v1/dots/{dot_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dotをゴミ箱へ移す（戻せる）
         * @description Day・一覧・日の詳細から外れ、`deletion_begins_at`から削除処理を始める（受理から7日）。
         *     これは削除処理を**始める**日時で、消え終わる時刻ではない。既にゴミ箱の中なら`404`。
         */
        post: operations["trashDot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/dots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ゴミ箱の中のDotを、ゴミ箱へ移した新しい順に取得する */
        get: operations["listTrashedDots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/dots/{dot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ゴミ箱の中のDotを元へ戻す
         * @description 元の`date`の日へ戻る。ゴミ箱に無い、または削除処理が始まったDotは`404`。
         */
        post: operations["restoreDot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457のProblem Details。`code`は拡張項目で、Webはこれで判定する。`title`と`detail`を
         *     そのまま画面に出さない。`detail`に日記本文・文字起こし・メールアドレスなどの個人データを
         *     入れない。`code`によって必ず返す拡張項目が違うので、codeごとのschemaに分ける
         *     （codeの集合は重ならない）。codeの意味とHTTP statusの対応は`contracts/README.md`の表。
         */
        Problem: components["schemas"]["ProblemGeneral"] | components["schemas"]["ProblemValidationFailed"] | components["schemas"]["ProblemRateLimited"] | components["schemas"]["ProblemRetryExpired"];
        /** @description 拡張項目を持たないcode */
        ProblemGeneral: {
            /** @description `urn:focus-on-dot:problem:<code>`の形のURN（識別子。実domainが未確定のため取得可能なURLにしない） */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @enum {string} */
            code: "unauthenticated" | "session_expired" | "email_unconfirmed" | "csrf_invalid" | "invalid_credentials" | "reauthentication_failed" | "google_reauthentication_required" | "token_invalid" | "token_expired" | "cursor_invalid" | "not_found" | "account_deletion_in_progress" | "attempt_invalid" | "attempt_expired" | "audio_too_large" | "unsupported_audio_type" | "retry_not_allowed" | "generation_completed" | "deletion_failed" | "internal_error";
        };
        /** @description `validation_failed`。項目ごとの理由を必ず返す */
        ProblemValidationFailed: {
            /** @description `urn:focus-on-dot:problem:<code>`の形のURN（識別子。実domainが未確定のため取得可能なURLにしない） */
            type: string;
            title: string;
            /** @enum {integer} */
            status: 422;
            detail?: string;
            /** @enum {string} */
            code: "validation_failed";
            errors: components["schemas"]["FieldError"][];
        };
        /** @description `rate_limited`。待つ秒数を必ず返す */
        ProblemRateLimited: {
            /** @description `urn:focus-on-dot:problem:<code>`の形のURN（識別子。実domainが未確定のため取得可能なURLにしない） */
            type: string;
            title: string;
            /** @enum {integer} */
            status: 429;
            detail?: string;
            /** @enum {string} */
            code: "rate_limited";
            retry_after_seconds: number;
        };
        /** @description `retry_expired`。過ぎた再試行期限を必ず返す */
        ProblemRetryExpired: {
            /** @description `urn:focus-on-dot:problem:<code>`の形のURN（識別子。実domainが未確定のため取得可能なURLにしない） */
            type: string;
            title: string;
            /** @enum {integer} */
            status: 409;
            detail?: string;
            /** @enum {string} */
            code: "retry_expired";
            /** Format: date-time */
            retry_expires_at: string;
        };
        FieldError: {
            /** @example sentence */
            field: string;
            /**
             * @description `taken`は使わない予約値（登録の有無を明かさないため）
             * @enum {string}
             */
            code: "required" | "too_long" | "invalid_format" | "out_of_range" | "not_allowed" | "taken";
        };
        /** @description `authenticated`で形が分かれる。未認証でもCSRF tokenは返す。 */
        Session: components["schemas"]["SessionAuthenticated"] | components["schemas"]["SessionAnonymous"];
        SessionAuthenticated: {
            /** @enum {boolean} */
            authenticated: true;
            csrf_token: string;
            /**
             * Format: date-time
             * @description 認証成功から7日。利用では延長しない
             */
            expires_at: string;
            user: components["schemas"]["SessionUser"];
            /**
             * @description `deletion_in_progress`なら退会の状況画面へ
             * @enum {string}
             */
            account_status: "active" | "deletion_in_progress";
        };
        SessionAnonymous: {
            /** @enum {boolean} */
            authenticated: false;
            csrf_token: string;
        };
        SessionUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            email_confirmed: boolean;
            sign_in_methods: ("password" | "google")[];
        };
        Credentials: {
            /** Format: email */
            email: string;
            /**
             * Format: password
             * @description loginでは長さを確かめない（登録・再設定の方針はNewCredentials）
             */
            password: string;
        };
        NewCredentials: {
            /** Format: email */
            email: string;
            /**
             * Format: password
             * @description 8〜128文字。文字種は問わない。合わなければ`validation_failed`で、8文字未満は`out_of_range`、128文字超は`too_long`
             */
            password: string;
        };
        EmailOnly: {
            /** Format: email */
            email: string;
        };
        TokenOnly: {
            token: string;
        };
        PasswordReset: {
            token: string;
            /**
             * Format: password
             * @description 8〜128文字。文字種は問わない。合わなければ`validation_failed`で、8文字未満は`out_of_range`、128文字超は`too_long`
             */
            password: string;
        };
        GoogleAuthStart: {
            authenticity_token: string;
            /**
             * @default sign_in
             * @enum {string}
             */
            intent: "sign_in" | "reauthenticate";
            /**
             * @description ログイン後に戻るSPAの画面のpath。英数字・`-`・`_`・`/`だけからなる素のpath
             *     （正規表現`/(?:[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*)?`）に**文字列全体で**一致するものだけを
             *     使う。serverは行単位で一致する`^`・`$`ではなく、文字列全体を表す`\A`・`\z`で照合する
             *     （Rubyの`^`・`$`は改行の前後でも一致し、`/\n/evil.example`を通してしまうため）。合わない値は
             *     拒否せず無視し、`/`へ戻す（open redirectを防ぎつつ、ログインそのものは失敗させない）
             */
            return_to?: string;
        };
        AccountDeletionRequest: {
            /**
             * Format: password
             * @description password利用者は必須
             */
            current_password?: string;
        };
        AccountDeletion: {
            /**
             * @description `in_progress`: 進行中の処理の終了と削除を待っている（通常は数秒、長い録音の文字起こし中は
             *     数分かかり得る）。`failed`: 削除の途中で失敗した。完了とは扱わない。serverが自動で再実行し、
             *     Webは`DELETE /api/v1/account`でいますぐやり直すこともできる。
             * @enum {string}
             */
            status: "in_progress" | "completed" | "failed";
        };
        RecordingAttempt: {
            /**
             * Format: uuid
             * @description 処理ID・冪等性key・録音attemptの識別子を兼ねる。serverが発行するUUID v4で、AWSアカウント内で
             *     一意（DBでも一意制約を持つ）。利用者・日付などの推測できる値を含まない。
             */
            id: string;
            /**
             * @description serverが暗号化・署名した値（id・利用者・started_at・期限を含む）。Webは解釈せず、memoryに
             *     だけ置いて`POST /api/v1/dots`の`X-Recording-Attempt` headerで返す。
             */
            attempt_token: string;
            /**
             * Format: date-time
             * @description 録音開始操作をserverが受理した時刻。Dotの`date`の根拠
             */
            started_at: string;
            /**
             * Format: date-time
             * @description このattemptで送信できる期限（発行から2時間）。受理後の再試行期限とは別
             */
            expires_at: string;
        };
        DotUpload: {
            /**
             * Format: binary
             * @description `audio/webm`（opus）または`audio/mp4`。32MBまで
             */
            audio: string;
            /** @description Webが計測した録音の長さ（最長30分） */
            duration_seconds: number;
        };
        /**
         * @description 生成の状態。`status`で形が分かれ、状態ごとに必ず返す項目が決まっている。
         *     `processing`: 送信・文字起こし・生成のいずれかの途中。
         *     `succeeded`: Dotを保存した。
         *     `failed`: 失敗した。`retryable`と`failure`で次の操作が決まる。
         *     `expired`: 再試行の期限を過ぎ、預かっていた音声の削除処理に入った。録り直しが必要。
         *       後片付けが終わると処理の記録が消え、以後は`404`になる。
         */
        Generation: components["schemas"]["GenerationProcessing"] | components["schemas"]["GenerationSucceeded"] | components["schemas"]["GenerationFailed"] | components["schemas"]["GenerationExpired"];
        GenerationProcessing: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "processing";
            /**
             * @description 画面の進捗表示に使う
             * @enum {string}
             */
            stage: "uploading" | "transcribing" | "generating";
            /** Format: date-time */
            started_at: string;
            /** @enum {boolean} */
            retryable: false;
            retry_expires_at: components["schemas"]["RetryExpiresAt"];
            /** @description 次に取得するまでの秒数 */
            poll_after_seconds: number;
        };
        /** @description 成功後は後片付けで処理の記録が消え、期限を持たないため`retry_expires_at`を返さない。 */
        GenerationSucceeded: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "succeeded";
            /** Format: date-time */
            started_at: string;
            /** @enum {boolean} */
            retryable: false;
            dot: components["schemas"]["Dot"];
            transcript: components["schemas"]["Transcript"];
        };
        GenerationFailed: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            /** Format: date-time */
            started_at: string;
            /** @description 期限内かつ録り直さずにやり直せるときだけ`true` */
            retryable: boolean;
            retry_expires_at: components["schemas"]["RetryExpiresAt"];
            failure: components["schemas"]["GenerationFailure"];
        };
        GenerationExpired: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "expired";
            /** Format: date-time */
            started_at: string;
            /** @enum {boolean} */
            retryable: false;
            retry_expires_at: components["schemas"]["RetryExpiresAt"];
        };
        /**
         * Format: date-time
         * @description 受理から24時間の再試行期限。音声が残っている間だけ画面に出す。消え終わる時刻ではない。
         */
        RetryExpiresAt: string;
        GenerationFailure: {
            /**
             * @description `processing_failed`: 文字起こし・生成・保存のいずれかで失敗。`retry`で再試行できる
             *       （どこから再開するかはserverが決め、契約には出さない）。
             *     `upload_incomplete`: 音声が届ききらなかった。録音画面にいる間だけ、同じattemptで
             *       `POST /api/v1/dots`へ送り直せる。
             *     `empty_recording`: 無音・極端に短い。再試行できず、録り直しを案内する。
             * @enum {string}
             */
            kind: "processing_failed" | "upload_incomplete" | "empty_recording";
        };
        /** @description 文字起こし全文。`status`で形が分かれる */
        Transcript: components["schemas"]["TranscriptAvailable"] | components["schemas"]["TranscriptUnavailable"];
        TranscriptAvailable: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "available";
            /** @description 文字起こし全文 */
            text: string;
        };
        /**
         * @description serverはもう全文を返さない（受領通知の受理後、または保持期間の経過後）。どちらだったかは
         *     返さない。後片付けで処理の記録が消えると、serverにも区別が残らないため。Webは`sessionStorage`に
         *     全文があれば表示し、無ければ「この端末には全文がない」と示す。Dotは残っている。
         */
        TranscriptUnavailable: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "unavailable";
        };
        Dot: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date
             * @description `started_at`から算出したAsia/Tokyoの暦日
             */
            date: string;
            /**
             * Format: date-time
             * @description 録音開始操作をserverが受理した時刻（UTC）。並びと同日の区別に使う
             */
            started_at: string;
            duration_seconds: number;
            /** @description 今日の一文。空文字を許す */
            sentence: string;
            /** @description 話した内容の要約。空文字を許す */
            summary: string;
        };
        DotUpdate: {
            sentence?: string;
            summary?: string;
        };
        TrashedDot: components["schemas"]["Dot"] & {
            /** Format: date-time */
            trashed_at: string;
            /**
             * Format: date-time
             * @description 削除処理を始める日時（受理から7日）。消え終わる時刻ではない
             */
            deletion_begins_at: string;
        };
        TrashedDotList: {
            items: components["schemas"]["TrashedDot"][];
            next_cursor: string | null;
        };
        DaySummary: {
            /** Format: date */
            date: string;
            /** @description その日のゴミ箱外のDotの件数 */
            dot_count: number;
            /**
             * Format: uuid
             * @description その日の最新のDot。日の詳細へ行くキーには`date`を使う
             */
            latest_dot_id: string;
        };
        DayList: {
            /**
             * Format: date
             * @description serverが決めた今日の日付（「今日」のラベルに使う）
             */
            today: string;
            items: components["schemas"]["DaySummary"][];
            next_cursor: string | null;
        };
        /** @description 今日の記録の有無で形が分かれる。記録があれば最新のDotを必ず返す */
        Today: components["schemas"]["TodayRecorded"] | components["schemas"]["TodayNotRecorded"];
        TodayRecorded: {
            /** Format: date */
            date: string;
            dot_count: number;
            latest_dot: components["schemas"]["Dot"];
        };
        TodayNotRecorded: {
            /** Format: date */
            date: string;
            /** @enum {integer} */
            dot_count: 0;
        };
        DayDetail: {
            /** Format: date */
            date: string;
            dots: components["schemas"]["Dot"][];
            next_cursor: string | null;
        };
    };
    responses: {
        /** @description `unauthenticated`（未login）または`session_expired`（7日の期限切れ） */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `email_unconfirmed`（メール未確認の利用者はDotを扱えない）または`csrf_invalid` */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `csrf_invalid`: CSRF tokenが無いか一致しない。Webは`GET /api/v1/session`で取り直して1回だけ再送してよい */
        CsrfInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `not_found`: 存在しない・他人の・ゴミ箱の中（ゴミ箱のendpoint以外）のresource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `account_deletion_in_progress`: 退会を受理済み */
        AccountDeletionInProgress: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `validation_failed`: 入力が不正。`errors`に項目ごとの理由 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `token_invalid`（不正・使用済み）または`token_expired` */
        TokenRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `cursor_invalid`: cursorを解釈できない。Webは先頭から取り直す */
        CursorInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `rate_limited`: 試行回数の制限。認証まわりはloginの失敗がIPごとに1時間50回、メール
         *     （登録・確認の再送・password再設定）の送信がIPごとに1時間20回。録音・送信・再試行
         *     （外部の文字起こし・生成の費用がかかる操作）の具体値と採否はTASK-009で決める
         */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `internal_error`: 想定外の失敗 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
        CsrfToken: string;
        /** @description 前回のresponseの`next_cursor`。Webは中身を解釈しない */
        Cursor: string;
        /**
         * @description `POST /api/v1/recording_attempts`で受け取った`attempt_token`。multipartを解釈する前に検証
         *     できるようheaderで渡す
         */
        RecordingAttempt: string;
        /** @description 処理ID（＝録音attemptのid） */
        GenerationId: string;
        DotId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認証状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description login成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description `invalid_credentials`: メールアドレスまたはpasswordが違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `email_unconfirmed`（メール未確認）または`csrf_invalid` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description logoutした */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            500: components["responses"]["InternalError"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCredentials"];
            };
        };
        responses: {
            /** @description 受け付けた（本文なし） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    resendConfirmation: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnly"];
            };
        };
        responses: {
            /** @description 受け付けた（本文なし） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmEmail: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenOnly"];
            };
        };
        responses: {
            /** @description 確認した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            422: components["responses"]["TokenRejected"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnly"];
            };
        };
        responses: {
            /** @description 受け付けた（本文なし） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description 再設定した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            /** @description `token_invalid` / `token_expired` / `validation_failed`（password方針） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    unlockAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenOnly"];
            };
        };
        responses: {
            /** @description 解除した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
            /** @description `token_invalid`: 不正・使用済み */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    startGoogleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["GoogleAuthStart"];
            };
        };
        responses: {
            /** @description Googleの認証画面へredirectする */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalid"];
        };
    };
    googleAuthCallback: {
        parameters: {
            query?: {
                state?: string;
                code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SPAへredirectする */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AccountDeletionRequest"];
            };
        };
        responses: {
            /** @description 受け付けた */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletion"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description `reauthentication_failed` / `google_reauthentication_required` / `csrf_invalid` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccountDeletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退会の状況 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletion"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createRecordingAttempt: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 発行した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingAttempt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createDot: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /**
                 * @description `POST /api/v1/recording_attempts`で受け取った`attempt_token`。multipartを解釈する前に検証
                 *     できるようheaderで渡す
                 */
                "X-Recording-Attempt": components["parameters"]["RecordingAttempt"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DotUpload"];
            };
        };
        responses: {
            /** @description 受け付けた（または同じattemptの既存の処理） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            /** @description `audio_too_large`: 32MBを超えた */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `unsupported_audio_type`: 受容しない音声形式 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `attempt_expired` / `attempt_invalid` / `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 生成の状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelGeneration: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取り消しを受け付けた（本文なし） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description `generation_completed` / `account_deletion_in_progress` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    retryGeneration: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 再試行を受け付けた */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description `retry_expired` / `retry_not_allowed` / `account_deletion_in_progress` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTranscript: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 処理ID（＝録音attemptのid） */
                generation_id: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除を受け付けた（本文なし） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
        };
    };
    listDays: {
        parameters: {
            query?: {
                /** @description 前回のresponseの`next_cursor`。Webは中身を解釈しない */
                cursor?: components["parameters"]["Cursor"];
                /** @description 1回に返す日数 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 日単位の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayList"];
                };
            };
            400: components["responses"]["CursorInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 今日の状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Today"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
        };
    };
    getDay: {
        parameters: {
            query?: {
                /** @description 前回のresponseの`next_cursor`。Webは中身を解釈しない */
                cursor?: components["parameters"]["Cursor"];
                /** @description 1回に返すDotの件数 */
                limit?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Asia/Tokyoの暦日
                 * @example 2026-09-28
                 */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description その日のDot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayDetail"];
                };
            };
            400: components["responses"]["CursorInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteDotPermanently: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 完全削除した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
            /** @description `deletion_failed`: 削除の途中で失敗した。Dotは残っている扱い */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateDot: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DotUpdate"];
            };
        };
        responses: {
            /** @description 編集後のDot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dot"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    trashDot: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゴミ箱へ移した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashedDot"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
        };
    };
    listTrashedDots: {
        parameters: {
            query?: {
                /** @description 前回のresponseの`next_cursor`。Webは中身を解釈しない */
                cursor?: components["parameters"]["Cursor"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゴミ箱の中のDot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashedDotList"];
                };
            };
            400: components["responses"]["CursorInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["AccountDeletionInProgress"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    restoreDot: {
        parameters: {
            query?: never;
            header: {
                /** @description `GET /api/v1/session`（login後は`POST /api/v1/session`）のresponseで受け取ったtoken */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                dot_id: components["parameters"]["DotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 戻したDot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dot"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AccountDeletionInProgress"];
            500: components["responses"]["InternalError"];
        };
    };
}
